### ISSUE TITLE
 If I want at 50 meters distance?

### ISSUE THREAD

**Issue by hoolanla** [limpkin/cdm324_backpack#2]
I got it But from the test, it can only work for 10 meters distance. If I want at 50 meters distance, what should I do? Please also recommend

**Comment by limpkin** [comment]
you'll need to change the resistor values to amplify the signal more.

**Comment by hoolanla** [comment]
You mean having to fix the CDM324_backpack again? Oh, I expect the CDM324_backpack , which has an extended circuit, can do 50 meters distance. Do you have other products? That can extend the signal up to 50 meters distance.   
Thank you

**Comment by limpkin** [comment]
I'm afraid no.
