### ISSUE TITLE
How can we do if we don't know how to use Isis

### ISSUE THREAD

**Issue by FrenchStudent** [limpkin/cdm324_backpack#3]
Hi, I'm a student and I want to know if it's possible to get the fritzing of this project.
Ty for you're answer.

**Comment by limpkin** [comment]
we don't have the fritzing.

**Comment by will-code-for-pizza** [comment]
Hi Limpkin... So if you do nt have Fritzing... would it be possible for you to draw a simple cabeling schema for us how to connect the CDM324 to arduino ?

**Comment by limpkin** [comment]
are you sure you're commenting on the right issue in the right repository? 
do you maybe meant to comment on https://github.com/limpkin/cdm324_fft ?
